data:
  path: "data/rnn_task.pkl"
  train_ratio: 0.8
  batch_size: 128
  shuffle: True
  num_workers: 4
model:
  hidden_dim: 128
train:
  n_epochs: 10
  criterion: MSELoss
  optimizer:
    name: Adam
    lr: 1e-4
  patience: 7
  verbose: True
  checkpoint_path: "checkpoints/rnn"